// Generated by Wrangler on Tue Jun 25 2024 15:55:19 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database;
}
